services:
  wiki:
    build:
      context: ./KiWiki_wiki
    ports:
      - "8001:8000"
    env_file:
      - ./KiWiki_wiki/.env
      
  entry:
    build:
      context: ./KiWiki_entry
    ports:
      - "8002:8000"
    env_file:
      - ./KiWiki_entry/.env
      
  commentaries:
    build:
      context: ./KiWiki_commentaries  
    ports:
      - "8003:8000"
    env_file:
      - ./KiWiki_commentaries/.env 
      
  notifications:
    build:
      context: ./KiWiki_notifications
    ports:
      - "8004:8000"
    env_file:
      - ./KiWiki_notifications/.env
      
  version:
    build:
      context: ./KiWiki_version
    ports:
      - "8005:8000"
    env_file:
      - ./KiWiki_version/.env

  user:
    build:
      context: ./KiWiki_user
    ports:
      - "8006:8000"
    env_file:
      - ./KiWiki_user/.env

  main_controller:
    build:
      context: ./KiWiki_main_controller 
    ports:
      - "8000:8000"
