# Test your FastAPI endpoints

GET http://127.0.0.1:8000/wiki/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/notification/
Accept: application/json

###

POST http://127.0.0.1:8000/notification/
Content-Type: application/json

{
"title": "Notificación de borrado de la Wiki Guerra",
"user": "Pepito",
"notifType": "Wiki removal authorization"
}